name: release-version

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'major, minor, or patch'
        required: true
        default: 'patch'

jobs:

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set Options
        id: options
        run: |
          echo "Received ${{ github.event.inputs.release }}"
          case "${{ github.event.inputs.release }}" in
            major|minor|patch) echo "Input valid";;
            *)                 echo "Input not valid" && exit 1 ;;
          esac
          echo "::set-output name=release::${{ github.event.inputs.release }}"

      - name: Print Options
        run: echo "Publishing release type $RELEASE"
        env: 
          RELEASE: ${{ steps.options.outputs.release }}
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Update version
        run: npm version $RELEASE
        env: 
          RELEASE: ${{ steps.options.outputs.release }}

      - name: Push changes
        run: |-
          git config user.name "releasebot"
          git config user.email "actions@users.noreply.github.com"
          git push --follow-tags
