name: release-version

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release type: major, minor, or patch'
        required: true
        default: 'patch'

concurrency: 
  group: 'release'
  cancel-in-progress: false

jobs:

  release-version:
    runs-on: ubuntu-latest
    steps:

      - name: Validate branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This action may only be run from the main branch. Selected: ${{ github.ref }}"
          exit 1

      - name: Validate options
        id: options
        run: |
          echo "Release type: ${{ github.event.inputs.release }}"
          case "${{ github.event.inputs.release }}" in
            major|minor|patch) echo "Input valid";;
            *)                 echo "Input not valid" && exit 1 ;;
          esac
          echo "::set-output name=release::${{ github.event.inputs.release }}"
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Setup git
        run: |-
          git config user.name "Release Bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Update version
        run: npm version $RELEASE --no-commit-hooks
        env: 
          RELEASE: ${{ steps.options.outputs.release }}

      - name: Push changes
        run: git push --follow-tags --force
